(setq faits nil)
(setq regles nil)
(setq iteration 0)
(setq liste_champions '( "camille" "lulu" "lux" "leesin" "yasuo" "caitlyn" "yone" "jinx" "jhin" "zed" "jayce" "irelia" "yuumi" "morgana" "jax" "viktor" "thresh" "blitzcrank" "nami" "viego" "graves" "masteryi" "teemo" "sett" "leona" "vayne" "kayn" "kassadin" "talon" "darius" "tryndamere" "vex" "ezreal" "khazix" "shen" "leblanc" "drmundo" "katarina" "soraka" "shaco" "pyke" "fiora" "nasus" "hecarim" "lucian" "rakan" "nautilus" "tahmkench" "ekko" "sylas" "karma" "xinzhao" "malphite" "warwick" "missfortune" "garen" "janna" "akali" "chogath" "urgot" "xerath" "ornn" "mordekaiser" "sona" "vladimir" "riven" "senna" "zac" "jarvaniv" "nocturne" "akshan" "trundle" "kayle" "nunu" "twistedfate" "ahri" "zilean" "veigar" "ashe" "aurelionsol" "sion" "sejuani" "alistar" "brand" "bard" "corki" "kaisa" "anivia" "nidalee" "draven" "gangplank" "braum" "twitch" "zyra" "rammus" "karthus" "kindred" "syndra" "fizz" "singed" "zoe" "galio" "seraphine" "malzahar" "taliyah" "rell" "gwen" "reksai" "kled" "rumble" "fiddlesticks" "velkoz" "amumu" "maokai" "yorick" "lissandra" "kogmaw" "orianna" "annie" "qiyana" "ziggs" "xayah" "poppy" "kennen" "diana" "aatrox" "samira" "tristana" "skarner" "renekton" "lillia" "elise" "swain" "monkeyking" "heimerdinger" "evelynn" "sivir" "cassiopeia" "gragas" "aphelios" "gnar" "udyr" "taric" "quinn" "neeko" "ryze" "volibear" "ivern" "shyvana" "pantheon" "kalista" "rengar" "illaoi" "azir" "varus" "olaf"))

(setq champions_adversaire '("zed" "teemo" "malphite"))


;;fonction pour ajouter un fait dans la bdf, ou modifer un fait deja present
(defun ajouteFait (fait)
    (let
    (( indice -1))
  (if (assoc (car fait) faits) ;;si element dans la liste
      (loop for x in faits do
       (setq indice (+ indice 1))
       (if (eq (car x) (car fait))
           (setf (nth indice faits) (list(car x) (cadr fait)))
         )
      )
    (setq faits (cons fait faits)))
      ))

(defun ajouteFaitContre (fait)
  (if (string-equal "garenContre" (car fait)) (print "----------"))
    (let
        ((indice -1))
      (loop for x in faits do
            (setq indice (+ indice 1))
            (when (string-equal (car x) (car fait))              
              (setf (cadr(nth indice faits))(+ (cadr x) (cadr fait)))
              ))
      ))

(defun nombre_contre (champion)
  (cadr(assoc (concatenate 'string champion "Contre") faits :test #'string-equal))
  )

;;fonction qui remplit la bdf
(defun remplir_faits ()
  ;; on initialise tous les champions, de base disponible et sans contre
  (loop for champion in liste_champions do
        (ajouteFait (list (concatenate 'string champion "Dispo")T))
        (ajouteFait (list (concatenate 'string champion "Contre")0))
        )
  
  ;;ici les champions pick par l'equipe adversaire
  (loop for champion in champions_adversaire do
        (ajouteFait (list (concatenate 'string champion "Adversaire")T)))
  
  ;;ici la lane cible
  (ajouteFait '("top" T))
  
  ;;ici la liste des champions maitrises par le joueur qui pick
  (ajouteFait '("camilleConnu" T))
  (ajouteFait '("jaxConnu" T))
  (ajouteFait '("yoneConnu" T))
  (ajouteFait '("ireliaConnu" T))
  (ajouteFait '("mundoConnu" T))
  (ajouteFait '("sionConnu" T))
  (ajouteFait '("jayceConnu" T))
  (ajouteFait '("garenConnu" T))
   
  )

(remplir_faits)

;;fonction qui insere une regle dans la bdr
(defun ajouteRegle (conditions result) 
	(setq regles (cons (list conditions result) regles))
)
;;fonction qui remplit la bdr
(defun remplir_regles()

  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Adversaire")T))
                     (list (concatenate 'string champion "Dispo")Nil)))
  

(ajouteRegle '(("camilleDispo" T) ("top" T)) '("camilleDispoLane"  T))
(ajouteRegle '(("luluDispo" T) ("support" T)) '("luluDispoLane"  T))
(ajouteRegle '(("luxDispo" T) ("support" T)) '("luxDispoLane"  T))
(ajouteRegle '(("leesinDispo" T) ("jungle" T)) '("leesinDispoLane"  T))
(ajouteRegle '(("yasuoDispo" T) ("mid" T)) '("yasuoDispoLane"  T))
(ajouteRegle '(("caitlynDispo" T) ("adc" T)) '("caitlynDispoLane"  T))
(ajouteRegle '(("yoneDispo" T) ("top" T)) '("yoneDispoLane"  T))
(ajouteRegle '(("jinxDispo" T) ("adc" T)) '("jinxDispoLane"  T))
(ajouteRegle '(("jhinDispo" T) ("adc" T)) '("jhinDispoLane"  T))
(ajouteRegle '(("zedDispo" T) ("mid" T)) '("zedDispoLane"  T))
(ajouteRegle '(("jayceDispo" T) ("top" T)) '("jayceDispoLane"  T))
(ajouteRegle '(("ireliaDispo" T) ("top" T)) '("ireliaDispoLane"  T))
(ajouteRegle '(("yuumiDispo" T) ("support" T)) '("yuumiDispoLane"  T))
(ajouteRegle '(("morganaDispo" T) ("support" T)) '("morganaDispoLane"  T))
(ajouteRegle '(("jaxDispo" T) ("top" T)) '("jaxDispoLane"  T))
(ajouteRegle '(("yoneDispo" T) ("mid" T)) '("yoneDispoLane"  T))
(ajouteRegle '(("viktorDispo" T) ("mid" T)) '("viktorDispoLane"  T))
(ajouteRegle '(("threshDispo" T) ("support" T)) '("threshDispoLane"  T))
(ajouteRegle '(("blitzcrankDispo" T) ("support" T)) '("blitzcrankDispoLane"  T))
(ajouteRegle '(("namiDispo" T) ("support" T)) '("namiDispoLane"  T))
(ajouteRegle '(("viDispo" T) ("jungle" T)) '("viDispoLane"  T))
(ajouteRegle '(("viegoDispo" T) ("jungle" T)) '("viegoDispoLane"  T))
(ajouteRegle '(("gravesDispo" T) ("jungle" T)) '("gravesDispoLane"  T))
(ajouteRegle '(("masteryiDispo" T) ("jungle" T)) '("masteryiDispoLane"  T))
(ajouteRegle '(("teemoDispo" T) ("top" T)) '("teemoDispoLane"  T))
(ajouteRegle '(("settDispo" T) ("top" T)) '("settDispoLane"  T))
(ajouteRegle '(("leonaDispo" T) ("support" T)) '("leonaDispoLane"  T))
(ajouteRegle '(("vayneDispo" T) ("adc" T)) '("vayneDispoLane"  T))
(ajouteRegle '(("luxDispo" T) ("mid" T)) '("luxDispoLane"  T))
(ajouteRegle '(("kaynDispo" T) ("jungle" T)) '("kaynDispoLane"  T))
(ajouteRegle '(("kassadinDispo" T) ("mid" T)) '("kassadinDispoLane"  T))
(ajouteRegle '(("talonDispo" T) ("jungle" T)) '("talonDispoLane"  T))
(ajouteRegle '(("dariusDispo" T) ("top" T)) '("dariusDispoLane"  T))
(ajouteRegle '(("tryndamereDispo" T) ("top" T)) '("tryndamereDispoLane"  T))
(ajouteRegle '(("vexDispo" T) ("mid" T)) '("vexDispoLane"  T))
(ajouteRegle '(("ezrealDispo" T) ("adc" T)) '("ezrealDispoLane"  T))
(ajouteRegle '(("khazixDispo" T) ("jungle" T)) '("khazixDispoLane"  T))
(ajouteRegle '(("shenDispo" T) ("top" T)) '("shenDispoLane"  T))
(ajouteRegle '(("leblancDispo" T) ("mid" T)) '("leblancDispoLane"  T))
(ajouteRegle '(("drmundoDispo" T) ("top" T)) '("drmundoDispoLane"  T))
(ajouteRegle '(("katarinaDispo" T) ("mid" T)) '("katarinaDispoLane"  T))
(ajouteRegle '(("sorakaDispo" T) ("support" T)) '("sorakaDispoLane"  T))
(ajouteRegle '(("shacoDispo" T) ("jungle" T)) '("shacoDispoLane"  T))
(ajouteRegle '(("pykeDispo" T) ("support" T)) '("pykeDispoLane"  T))
(ajouteRegle '(("fioraDispo" T) ("top" T)) '("fioraDispoLane"  T))
(ajouteRegle '(("nasusDispo" T) ("top" T)) '("nasusDispoLane"  T))
(ajouteRegle '(("hecarimDispo" T) ("jungle" T)) '("hecarimDispoLane"  T))
(ajouteRegle '(("lucianDispo" T) ("adc" T)) '("lucianDispoLane"  T))
(ajouteRegle '(("rakanDispo" T) ("support" T)) '("rakanDispoLane"  T))
(ajouteRegle '(("nautilusDispo" T) ("support" T)) '("nautilusDispoLane"  T))
(ajouteRegle '(("tahmkenchDispo" T) ("top" T)) '("tahmkenchDispoLane"  T))
(ajouteRegle '(("ekkoDispo" T) ("jungle" T)) '("ekkoDispoLane"  T))
(ajouteRegle '(("sylasDispo" T) ("mid" T)) '("sylasDispoLane"  T))
(ajouteRegle '(("karmaDispo" T) ("support" T)) '("karmaDispoLane"  T))
(ajouteRegle '(("xinzhaoDispo" T) ("jungle" T)) '("xinzhaoDispoLane"  T))
(ajouteRegle '(("malphiteDispo" T) ("top" T)) '("malphiteDispoLane"  T))
(ajouteRegle '(("warwickDispo" T) ("jungle" T)) '("warwickDispoLane"  T))
(ajouteRegle '(("missfortuneDispo" T) ("adc" T)) '("missfortuneDispoLane"  T))
(ajouteRegle '(("garenDispo" T) ("top" T)) '("garenDispoLane"  T))
(ajouteRegle '(("jannaDispo" T) ("support" T)) '("jannaDispoLane"  T))
(ajouteRegle '(("akaliDispo" T) ("mid" T)) '("akaliDispoLane"  T))
(ajouteRegle '(("chogathDispo" T) ("top" T)) '("chogathDispoLane"  T))
(ajouteRegle '(("urgotDispo" T) ("top" T)) '("urgotDispoLane"  T))
(ajouteRegle '(("xerathDispo" T) ("support" T)) '("xerathDispoLane"  T))
(ajouteRegle '(("ornnDispo" T) ("top" T)) '("ornnDispoLane"  T))
(ajouteRegle '(("mordekaiserDispo" T) ("top" T)) '("mordekaiserDispoLane"  T))
(ajouteRegle '(("sonaDispo" T) ("support" T)) '("sonaDispoLane"  T))
(ajouteRegle '(("vladimirDispo" T) ("mid" T)) '("vladimirDispoLane"  T))
(ajouteRegle '(("rivenDispo" T) ("top" T)) '("rivenDispoLane"  T))
(ajouteRegle '(("sennaDispo" T) ("support" T)) '("sennaDispoLane"  T))
(ajouteRegle '(("zacDispo" T) ("jungle" T)) '("zacDispoLane"  T))
(ajouteRegle '(("gravesDispo" T) ("top" T)) '("gravesDispoLane"  T))
(ajouteRegle '(("jarvanivDispo" T) ("jungle" T)) '("jarvanivDispoLane"  T))
(ajouteRegle '(("nocturneDispo" T) ("jungle" T)) '("nocturneDispoLane"  T))
(ajouteRegle '(("yasuoDispo" T) ("top" T)) '("yasuoDispoLane"  T))
(ajouteRegle '(("akshanDispo" T) ("mid" T)) '("akshanDispoLane"  T))
(ajouteRegle '(("trundleDispo" T) ("jungle" T)) '("trundleDispoLane"  T))
(ajouteRegle '(("kayleDispo" T) ("top" T)) '("kayleDispoLane"  T))
(ajouteRegle '(("nunuDispo" T) ("jungle" T)) '("nunuDispoLane"  T))
(ajouteRegle '(("vayneDispo" T) ("top" T)) '("vayneDispoLane"  T))
(ajouteRegle '(("twistedfateDispo" T) ("mid" T)) '("twistedfateDispoLane"  T))
(ajouteRegle '(("ahriDispo" T) ("mid" T)) '("ahriDispoLane"  T))
(ajouteRegle '(("zileanDispo" T) ("support" T)) '("zileanDispoLane"  T))
(ajouteRegle '(("veigarDispo" T) ("mid" T)) '("veigarDispoLane"  T))
(ajouteRegle '(("asheDispo" T) ("adc" T)) '("asheDispoLane"  T))
(ajouteRegle '(("aurelionsolDispo" T) ("mid" T)) '("aurelionsolDispoLane"  T))
(ajouteRegle '(("akaliDispo" T) ("top" T)) '("akaliDispoLane"  T))
(ajouteRegle '(("zileanDispo" T) ("mid" T)) '("zileanDispoLane"  T))
(ajouteRegle '(("xerathDispo" T) ("mid" T)) '("xerathDispoLane"  T))
(ajouteRegle '(("sionDispo" T) ("top" T)) '("sionDispoLane"  T))
(ajouteRegle '(("zedDispo" T) ("jungle" T)) '("zedDispoLane"  T))
(ajouteRegle '(("sejuaniDispo" T) ("jungle" T)) '("sejuaniDispoLane"  T))
(ajouteRegle '(("alistarDispo" T) ("support" T)) '("alistarDispoLane"  T))
(ajouteRegle '(("brandDispo" T) ("support" T)) '("brandDispoLane"  T))
(ajouteRegle '(("ireliaDispo" T) ("mid" T)) '("ireliaDispoLane"  T))
(ajouteRegle '(("bardDispo" T) ("support" T)) '("bardDispoLane"  T))
(ajouteRegle '(("corkiDispo" T) ("mid" T)) '("corkiDispoLane"  T))
(ajouteRegle '(("kaisaDispo" T) ("adc" T)) '("kaisaDispoLane"  T))
(ajouteRegle '(("aniviaDispo" T) ("mid" T)) '("aniviaDispoLane"  T))
(ajouteRegle '(("nidaleeDispo" T) ("jungle" T)) '("nidaleeDispoLane"  T))
(ajouteRegle '(("dravenDispo" T) ("adc" T)) '("dravenDispoLane"  T))
(ajouteRegle '(("gangplankDispo" T) ("top" T)) '("gangplankDispoLane"  T))
(ajouteRegle '(("braumDispo" T) ("support" T)) '("braumDispoLane"  T))
(ajouteRegle '(("twitchDispo" T) ("adc" T)) '("twitchDispoLane"  T))
(ajouteRegle '(("zyraDispo" T) ("support" T)) '("zyraDispoLane"  T))
(ajouteRegle '(("rammusDispo" T) ("jungle" T)) '("rammusDispoLane"  T))
(ajouteRegle '(("karthusDispo" T) ("adc" T)) '("karthusDispoLane"  T))
(ajouteRegle '(("viktorDispo" T) ("top" T)) '("viktorDispoLane"  T))
(ajouteRegle '(("kindredDispo" T) ("jungle" T)) '("kindredDispoLane"  T))
(ajouteRegle '(("syndraDispo" T) ("mid" T)) '("syndraDispoLane"  T))
(ajouteRegle '(("kayleDispo" T) ("mid" T)) '("kayleDispoLane"  T))
(ajouteRegle '(("fizzDispo" T) ("mid" T)) '("fizzDispoLane"  T))
(ajouteRegle '(("singedDispo" T) ("mid" T)) '("singedDispoLane"  T))
(ajouteRegle '(("zoeDispo" T) ("mid" T)) '("zoeDispoLane"  T))
(ajouteRegle '(("galioDispo" T) ("mid" T)) '("galioDispoLane"  T))
(ajouteRegle '(("seraphineDispo" T) ("mid" T)) '("seraphineDispoLane"  T))
(ajouteRegle '(("singedDispo" T) ("top" T)) '("singedDispoLane"  T))
(ajouteRegle '(("malzaharDispo" T) ("mid" T)) '("malzaharDispoLane"  T))
(ajouteRegle '(("chogathDispo" T) ("mid" T)) '("chogathDispoLane"  T))
(ajouteRegle '(("taliyahDispo" T) ("mid" T)) '("taliyahDispoLane"  T))
(ajouteRegle '(("rellDispo" T) ("support" T)) '("rellDispoLane"  T))
(ajouteRegle '(("gwenDispo" T) ("top" T)) '("gwenDispoLane"  T))
(ajouteRegle '(("reksaiDispo" T) ("jungle" T)) '("reksaiDispoLane"  T))
(ajouteRegle '(("tryndamereDispo" T) ("mid" T)) '("tryndamereDispoLane"  T))
(ajouteRegle '(("kledDispo" T) ("top" T)) '("kledDispoLane"  T))
(ajouteRegle '(("rumbleDispo" T) ("mid" T)) '("rumbleDispoLane"  T))
(ajouteRegle '(("ekkoDispo" T) ("mid" T)) '("ekkoDispoLane"  T))
(ajouteRegle '(("fiddlesticksDispo" T) ("jungle" T)) '("fiddlesticksDispoLane"  T))
(ajouteRegle '(("velkozDispo" T) ("mid" T)) '("velkozDispoLane"  T))
(ajouteRegle '(("amumuDispo" T) ("jungle" T)) '("amumuDispoLane"  T))
(ajouteRegle '(("maokaiDispo" T) ("support" T)) '("maokaiDispoLane"  T))
(ajouteRegle '(("yorickDispo" T) ("top" T)) '("yorickDispoLane"  T))
(ajouteRegle '(("lissandraDispo" T) ("mid" T)) '("lissandraDispoLane"  T))
(ajouteRegle '(("malphiteDispo" T) ("mid" T)) '("malphiteDispoLane"  T))
(ajouteRegle '(("gravesDispo" T) ("mid" T)) '("gravesDispoLane"  T))
(ajouteRegle '(("kogmawDispo" T) ("adc" T)) '("kogmawDispoLane"  T))
(ajouteRegle '(("veigarDispo" T) ("adc" T)) '("veigarDispoLane"  T))
(ajouteRegle '(("oriannaDispo" T) ("mid" T)) '("oriannaDispoLane"  T))
(ajouteRegle '(("annieDispo" T) ("mid" T)) '("annieDispoLane"  T))
(ajouteRegle '(("qiyanaDispo" T) ("mid" T)) '("qiyanaDispoLane"  T))
(ajouteRegle '(("ziggsDispo" T) ("adc" T)) '("ziggsDispoLane"  T))
(ajouteRegle '(("xayahDispo" T) ("adc" T)) '("xayahDispoLane"  T))
(ajouteRegle '(("poppyDispo" T) ("jungle" T)) '("poppyDispoLane"  T))
(ajouteRegle '(("kennenDispo" T) ("top" T)) '("kennenDispoLane"  T))
(ajouteRegle '(("seraphineDispo" T) ("adc" T)) '("seraphineDispoLane"  T))
(ajouteRegle '(("seraphineDispo" T) ("support" T)) '("seraphineDispoLane"  T))
(ajouteRegle '(("dianaDispo" T) ("mid" T)) '("dianaDispoLane"  T))
(ajouteRegle '(("aatroxDispo" T) ("top" T)) '("aatroxDispoLane"  T))
(ajouteRegle '(("samiraDispo" T) ("adc" T)) '("samiraDispoLane"  T))
(ajouteRegle '(("tristanaDispo" T) ("adc" T)) '("tristanaDispoLane"  T))
(ajouteRegle '(("skarnerDispo" T) ("jungle" T)) '("skarnerDispoLane"  T))
(ajouteRegle '(("renektonDispo" T) ("top" T)) '("renektonDispoLane"  T))
(ajouteRegle '(("lilliaDispo" T) ("jungle" T)) '("lilliaDispoLane"  T))
(ajouteRegle '(("eliseDispo" T) ("jungle" T)) '("eliseDispoLane"  T))
(ajouteRegle '(("swainDispo" T) ("support" T)) '("swainDispoLane"  T))
(ajouteRegle '(("monkeykingDispo" T) ("top" T)) '("monkeykingDispoLane"  T))
(ajouteRegle '(("heimerdingerDispo" T) ("adc" T)) '("heimerdingerDispoLane"  T))
(ajouteRegle '(("velkozDispo" T) ("support" T)) '("velkozDispoLane"  T))
(ajouteRegle '(("sennaDispo" T) ("adc" T)) '("sennaDispoLane"  T))
(ajouteRegle '(("trundleDispo" T) ("top" T)) '("trundleDispoLane"  T))
(ajouteRegle '(("evelynnDispo" T) ("jungle" T)) '("evelynnDispoLane"  T))
(ajouteRegle '(("taliyahDispo" T) ("support" T)) '("taliyahDispoLane"  T))
(ajouteRegle '(("brandDispo" T) ("mid" T)) '("brandDispoLane"  T))
(ajouteRegle '(("sivirDispo" T) ("adc" T)) '("sivirDispoLane"  T))
(ajouteRegle '(("cassiopeiaDispo" T) ("mid" T)) '("cassiopeiaDispoLane"  T))
(ajouteRegle '(("swainDispo" T) ("mid" T)) '("swainDispoLane"  T))
(ajouteRegle '(("shacoDispo" T) ("support" T)) '("shacoDispoLane"  T))
(ajouteRegle '(("akshanDispo" T) ("top" T)) '("akshanDispoLane"  T))
(ajouteRegle '(("gragasDispo" T) ("jungle" T)) '("gragasDispoLane"  T))
(ajouteRegle '(("apheliosDispo" T) ("adc" T)) '("apheliosDispoLane"  T))
(ajouteRegle '(("talonDispo" T) ("mid" T)) '("talonDispoLane"  T))
(ajouteRegle '(("sylasDispo" T) ("top" T)) '("sylasDispoLane"  T))
(ajouteRegle '(("swainDispo" T) ("adc" T)) '("swainDispoLane"  T))
(ajouteRegle '(("gnarDispo" T) ("top" T)) '("gnarDispoLane"  T))
(ajouteRegle '(("udyrDispo" T) ("jungle" T)) '("udyrDispoLane"  T))
(ajouteRegle '(("karthusDispo" T) ("jungle" T)) '("karthusDispoLane"  T))
(ajouteRegle '(("heimerdingerDispo" T) ("top" T)) '("heimerdingerDispoLane"  T))
(ajouteRegle '(("taricDispo" T) ("support" T)) '("taricDispoLane"  T))
(ajouteRegle '(("kennenDispo" T) ("mid" T)) '("kennenDispoLane"  T))
(ajouteRegle '(("amumuDispo" T) ("support" T)) '("amumuDispoLane"  T))
(ajouteRegle '(("quinnDispo" T) ("top" T)) '("quinnDispoLane"  T))
(ajouteRegle '(("yasuoDispo" T) ("adc" T)) '("yasuoDispoLane"  T))
(ajouteRegle '(("taliyahDispo" T) ("jungle" T)) '("taliyahDispoLane"  T))
(ajouteRegle '(("neekoDispo" T) ("mid" T)) '("neekoDispoLane"  T))
(ajouteRegle '(("jayceDispo" T) ("mid" T)) '("jayceDispoLane"  T))
(ajouteRegle '(("poppyDispo" T) ("top" T)) '("poppyDispoLane"  T))
(ajouteRegle '(("mordekaiserDispo" T) ("jungle" T)) '("mordekaiserDispoLane"  T))
(ajouteRegle '(("gragasDispo" T) ("top" T)) '("gragasDispoLane"  T))
(ajouteRegle '(("vladimirDispo" T) ("top" T)) '("vladimirDispoLane"  T))
(ajouteRegle '(("ziggsDispo" T) ("mid" T)) '("ziggsDispoLane"  T))
(ajouteRegle '(("qiyanaDispo" T) ("jungle" T)) '("qiyanaDispoLane"  T))
(ajouteRegle '(("ryzeDispo" T) ("mid" T)) '("ryzeDispoLane"  T))
(ajouteRegle '(("volibearDispo" T) ("top" T)) '("volibearDispoLane"  T))
(ajouteRegle '(("dianaDispo" T) ("jungle" T)) '("dianaDispoLane"  T))
(ajouteRegle '(("heimerdingerDispo" T) ("mid" T)) '("heimerdingerDispoLane"  T))
(ajouteRegle '(("ivernDispo" T) ("jungle" T)) '("ivernDispoLane"  T))
(ajouteRegle '(("shenDispo" T) ("support" T)) '("shenDispoLane"  T))
(ajouteRegle '(("shyvanaDispo" T) ("jungle" T)) '("shyvanaDispoLane"  T))
(ajouteRegle '(("pantheonDispo" T) ("mid" T)) '("pantheonDispoLane"  T))
(ajouteRegle '(("warwickDispo" T) ("top" T)) '("warwickDispoLane"  T))
(ajouteRegle '(("renektonDispo" T) ("mid" T)) '("renektonDispoLane"  T))
(ajouteRegle '(("cassiopeiaDispo" T) ("adc" T)) '("cassiopeiaDispoLane"  T))
(ajouteRegle '(("volibearDispo" T) ("jungle" T)) '("volibearDispoLane"  T))
(ajouteRegle '(("gragasDispo" T) ("support" T)) '("gragasDispoLane"  T))
(ajouteRegle '(("skarnerDispo" T) ("top" T)) '("skarnerDispoLane"  T))
(ajouteRegle '(("lilliaDispo" T) ("top" T)) '("lilliaDispoLane"  T))
(ajouteRegle '(("kalistaDispo" T) ("adc" T)) '("kalistaDispoLane"  T))
(ajouteRegle '(("akshanDispo" T) ("adc" T)) '("akshanDispoLane"  T))
(ajouteRegle '(("cassiopeiaDispo" T) ("top" T)) '("cassiopeiaDispoLane"  T))
(ajouteRegle '(("rengarDispo" T) ("jungle" T)) '("rengarDispoLane"  T))
(ajouteRegle '(("monkeykingDispo" T) ("jungle" T)) '("monkeykingDispoLane"  T))
(ajouteRegle '(("karthusDispo" T) ("mid" T)) '("karthusDispoLane"  T))
(ajouteRegle '(("vexDispo" T) ("support" T)) '("vexDispoLane"  T))
(ajouteRegle '(("galioDispo" T) ("support" T)) '("galioDispoLane"  T))
(ajouteRegle '(("illaoiDispo" T) ("top" T)) '("illaoiDispoLane"  T))
(ajouteRegle '(("syndraDispo" T) ("adc" T)) '("syndraDispoLane"  T))
(ajouteRegle '(("rumbleDispo" T) ("top" T)) '("rumbleDispoLane"  T))
(ajouteRegle '(("maokaiDispo" T) ("top" T)) '("maokaiDispoLane"  T))
(ajouteRegle '(("veigarDispo" T) ("support" T)) '("veigarDispoLane"  T))
(ajouteRegle '(("aniviaDispo" T) ("support" T)) '("aniviaDispoLane"  T))
(ajouteRegle '(("azirDispo" T) ("mid" T)) '("azirDispoLane"  T))
(ajouteRegle '(("jaxDispo" T) ("jungle" T)) '("jaxDispoLane"  T))
(ajouteRegle '(("varusDispo" T) ("adc" T)) '("varusDispoLane"  T))
(ajouteRegle '(("sejuaniDispo" T) ("top" T)) '("sejuaniDispoLane"  T))
(ajouteRegle '(("gangplankDispo" T) ("mid" T)) '("gangplankDispoLane"  T))
(ajouteRegle '(("neekoDispo" T) ("support" T)) '("neekoDispoLane"  T))
(ajouteRegle '(("olafDispo" T) ("jungle" T)) '("olafDispoLane"  T))
(ajouteRegle '(("annieDispo" T) ("support" T)) '("annieDispoLane"  T))
(ajouteRegle '(("rengarDispo" T) ("top" T)) '("rengarDispoLane"  T))
(ajouteRegle '(("trundleDispo" T) ("support" T)) '("trundleDispoLane"  T))
(ajouteRegle '(("pantheonDispo" T) ("support" T)) '("pantheonDispoLane"  T))
(ajouteRegle '(("fiddlesticksDispo" T) ("support" T)) '("fiddlesticksDispoLane"  T))
(ajouteRegle '(("ivernDispo" T) ("support" T)) '("ivernDispoLane"  T))
(ajouteRegle '(("heimerdingerDispo" T) ("support" T)) '("heimerdingerDispoLane"  T))
(ajouteRegle '(("rumbleDispo" T) ("jungle" T)) '("rumbleDispoLane"  T))
(ajouteRegle '(("pantheonDispo" T) ("top" T)) '("pantheonDispoLane"  T))
(ajouteRegle '(("malphiteDispo" T) ("support" T)) '("malphiteDispoLane"  T))
(ajouteRegle '(("gwenDispo" T) ("jungle" T)) '("gwenDispoLane"  T))
(ajouteRegle '(("ryzeDispo" T) ("top" T)) '("ryzeDispoLane"  T))
(ajouteRegle '(("shyvanaDispo" T) ("top" T)) '("shyvanaDispoLane"  T))
(ajouteRegle '(("twitchDispo" T) ("support" T)) '("twitchDispoLane"  T))
(ajouteRegle '(("olafDispo" T) ("top" T)) '("olafDispoLane"  T))

  
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "DispoLane")T) (list (concatenate 'string champion "Connu")T))
                     (list (concatenate 'string champion "Jouable")T)))
    
(ajouteRegle '(("malphiteAdversaire" T) ("camilleDispoLane" T))
             (list "camilleContre" 5))
(ajouteRegle '(("zedAdversaire" T) ("camilleDispoLane" T))
             (list "camilleContre" -1))
(ajouteRegle '(("teemoAdversaire" T) ("garenDispoLane" T))
             (list "garenContre" 2))
(ajouteRegle '(("fizzAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  1)) 
(ajouteRegle '(("akshanAdversaire" T) ("fizzDispoLane" T)) (list "fizzContre"  -1))
(ajouteRegle '(("singedAdversaire" T) ("ekkoDispoLane" T)) (list "ekkoContre"  1)) 
(ajouteRegle '(("ekkoAdversaire" T) ("singedDispoLane" T)) (list "singedContre"  -1))
(ajouteRegle '(("zoeAdversaire" T) ("talonDispoLane" T)) (list "talonContre"  1)) 
(ajouteRegle '(("talonAdversaire" T) ("zoeDispoLane" T)) (list "zoeContre"  -1))
(ajouteRegle '(("galioAdversaire" T) ("qiyanaDispoLane" T)) (list "qiyanaContre"  1)) 
(ajouteRegle '(("qiyanaAdversaire" T) ("galioDispoLane" T)) (list "galioContre"  -1))
(ajouteRegle '(("seraphineAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  1)) 
(ajouteRegle '(("vexAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  -1))
(ajouteRegle '(("singedAdversaire" T) ("poppyDispoLane" T)) (list "poppyContre"  1)) 
(ajouteRegle '(("poppyAdversaire" T) ("singedDispoLane" T)) (list "singedContre"  -1))
(ajouteRegle '(("malzaharAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  1)) 
(ajouteRegle '(("chogathAdversaire" T) ("malzaharDispoLane" T)) (list "malzaharContre"  -1))
(ajouteRegle '(("chogathAdversaire" T) ("xerathDispoLane" T)) (list "xerathContre"  1)) 
(ajouteRegle '(("xerathAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  -1))
(ajouteRegle '(("taliyahAdversaire" T) ("zedDispoLane" T)) (list "zedContre"  1)) 
(ajouteRegle '(("zedAdversaire" T) ("taliyahDispoLane" T)) (list "taliyahContre"  -1))
(ajouteRegle '(("rellAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  1)) 
(ajouteRegle '(("neekoAdversaire" T) ("rellDispoLane" T)) (list "rellContre"  -1))
(ajouteRegle '(("gwenAdversaire" T) ("olafDispoLane" T)) (list "olafContre"  1)) 
(ajouteRegle '(("olafAdversaire" T) ("gwenDispoLane" T)) (list "gwenContre"  -1))
(ajouteRegle '(("reksaiAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("reksaiDispoLane" T)) (list "reksaiContre"  -1))
(ajouteRegle '(("tryndamereAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  1)) 
(ajouteRegle '(("annieAdversaire" T) ("tryndamereDispoLane" T)) (list "tryndamereContre"  -1))
(ajouteRegle '(("kledAdversaire" T) ("urgotDispoLane" T)) (list "urgotContre"  1)) 
(ajouteRegle '(("urgotAdversaire" T) ("kledDispoLane" T)) (list "kledContre"  -1))
(ajouteRegle '(("rumbleAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  1)) 
(ajouteRegle '(("pantheonAdversaire" T) ("rumbleDispoLane" T)) (list "rumbleContre"  -1))
(ajouteRegle '(("ekkoAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  1)) 
(ajouteRegle '(("neekoAdversaire" T) ("ekkoDispoLane" T)) (list "ekkoContre"  -1))
(ajouteRegle '(("fiddlesticksAdversaire" T) ("ekkoDispoLane" T)) (list "ekkoContre"  1)) 
(ajouteRegle '(("ekkoAdversaire" T) ("fiddlesticksDispoLane" T)) (list "fiddlesticksContre"  -1))
(ajouteRegle '(("velkozAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  1)) 
(ajouteRegle '(("akshanAdversaire" T) ("velkozDispoLane" T)) (list "velkozContre"  -1))
(ajouteRegle '(("amumuAdversaire" T) ("skarnerDispoLane" T)) (list "skarnerContre"  1)) 
(ajouteRegle '(("skarnerAdversaire" T) ("amumuDispoLane" T)) (list "amumuContre"  -1))
(ajouteRegle '(("maokaiAdversaire" T) ("sorakaDispoLane" T)) (list "sorakaContre"  1)) 
(ajouteRegle '(("sorakaAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  -1))
(ajouteRegle '(("yorickAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  1)) 
(ajouteRegle '(("gravesAdversaire" T) ("yorickDispoLane" T)) (list "yorickContre"  -1))
(ajouteRegle '(("lissandraAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  1)) 
(ajouteRegle '(("pantheonAdversaire" T) ("lissandraDispoLane" T)) (list "lissandraContre"  -1))
(ajouteRegle '(("malphiteAdversaire" T) ("singedDispoLane" T)) (list "singedContre"  1)) 
(ajouteRegle '(("singedAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  -1))
(ajouteRegle '(("gravesAdversaire" T) ("ahriDispoLane" T)) (list "ahriContre"  1)) 
(ajouteRegle '(("ahriAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  -1))
(ajouteRegle '(("kogmawAdversaire" T) ("cassiopeiaDispoLane" T)) (list "cassiopeiaContre"  1)) 
(ajouteRegle '(("cassiopeiaAdversaire" T) ("kogmawDispoLane" T)) (list "kogmawContre"  -1))
(ajouteRegle '(("veigarAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  1)) 
(ajouteRegle '(("namiAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  -1))
(ajouteRegle '(("oriannaAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  1)) 
(ajouteRegle '(("karthusAdversaire" T) ("oriannaDispoLane" T)) (list "oriannaContre"  -1))
(ajouteRegle '(("annieAdversaire" T) ("xerathDispoLane" T)) (list "xerathContre"  1)) 
(ajouteRegle '(("xerathAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  -1))
(ajouteRegle '(("qiyanaAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  1)) 
(ajouteRegle '(("gravesAdversaire" T) ("qiyanaDispoLane" T)) (list "qiyanaContre"  -1))
(ajouteRegle '(("ziggsAdversaire" T) ("sorakaDispoLane" T)) (list "sorakaContre"  1)) 
(ajouteRegle '(("sorakaAdversaire" T) ("ziggsDispoLane" T)) (list "ziggsContre"  -1))
(ajouteRegle '(("xayahAdversaire" T) ("jhinDispoLane" T)) (list "jhinContre"  1)) 
(ajouteRegle '(("jhinAdversaire" T) ("xayahDispoLane" T)) (list "xayahContre"  -1))
(ajouteRegle '(("poppyAdversaire" T) ("viegoDispoLane" T)) (list "viegoContre"  1)) 
(ajouteRegle '(("viegoAdversaire" T) ("poppyDispoLane" T)) (list "poppyContre"  -1))
(ajouteRegle '(("kennenAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  1)) 
(ajouteRegle '(("warwickAdversaire" T) ("kennenDispoLane" T)) (list "kennenContre"  -1))
(ajouteRegle '(("seraphineAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  1)) 
(ajouteRegle '(("maokaiAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  -1))
(ajouteRegle '(("seraphineAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  1)) 
(ajouteRegle '(("annieAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  -1))
(ajouteRegle '(("dianaAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  1)) 
(ajouteRegle '(("gravesAdversaire" T) ("dianaDispoLane" T)) (list "dianaContre"  -1))
(ajouteRegle '(("aatroxAdversaire" T) ("sionDispoLane" T)) (list "sionContre"  1)) 
(ajouteRegle '(("sionAdversaire" T) ("aatroxDispoLane" T)) (list "aatroxContre"  -1))
(ajouteRegle '(("samiraAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  1)) 
(ajouteRegle '(("vexAdversaire" T) ("samiraDispoLane" T)) (list "samiraContre"  -1))
(ajouteRegle '(("tristanaAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  1)) 
(ajouteRegle '(("maokaiAdversaire" T) ("tristanaDispoLane" T)) (list "tristanaContre"  -1))
(ajouteRegle '(("skarnerAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  1)) 
(ajouteRegle '(("warwickAdversaire" T) ("skarnerDispoLane" T)) (list "skarnerContre"  -1))
(ajouteRegle '(("renektonAdversaire" T) ("kennenDispoLane" T)) (list "kennenContre"  1)) 
(ajouteRegle '(("kennenAdversaire" T) ("renektonDispoLane" T)) (list "renektonContre"  -1))
(ajouteRegle '(("lilliaAdversaire" T) ("xinzhaoDispoLane" T)) (list "xinzhaoContre"  1)) 
(ajouteRegle '(("xinzhaoAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  -1))
(ajouteRegle '(("eliseAdversaire" T) ("ekkoDispoLane" T)) (list "ekkoContre"  1)) 
(ajouteRegle '(("ekkoAdversaire" T) ("eliseDispoLane" T)) (list "eliseContre"  -1))
(ajouteRegle '(("swainAdversaire" T) ("shenDispoLane" T)) (list "shenContre"  1)) 
(ajouteRegle '(("shenAdversaire" T) ("swainDispoLane" T)) (list "swainContre"  -1))
(ajouteRegle '(("monkeykingAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  1)) 
(ajouteRegle '(("lilliaAdversaire" T) ("monkeykingDispoLane" T)) (list "monkeykingContre"  -1))
(ajouteRegle '(("heimerdingerAdversaire" T) ("asheDispoLane" T)) (list "asheContre"  1)) 
(ajouteRegle '(("asheAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  -1))
(ajouteRegle '(("velkozAdversaire" T) ("brandDispoLane" T)) (list "brandContre"  1)) 
(ajouteRegle '(("brandAdversaire" T) ("velkozDispoLane" T)) (list "velkozContre"  -1))
(ajouteRegle '(("sennaAdversaire" T) ("jinxDispoLane" T)) (list "jinxContre"  1)) 
(ajouteRegle '(("jinxAdversaire" T) ("sennaDispoLane" T)) (list "sennaContre"  -1))
(ajouteRegle '(("trundleAdversaire" T) ("drmundoDispoLane" T)) (list "drmundoContre"  1)) 
(ajouteRegle '(("drmundoAdversaire" T) ("trundleDispoLane" T)) (list "trundleContre"  -1))
(ajouteRegle '(("evelynnAdversaire" T) ("viegoDispoLane" T)) (list "viegoContre"  1)) 
(ajouteRegle '(("viegoAdversaire" T) ("evelynnDispoLane" T)) (list "evelynnContre"  -1))
(ajouteRegle '(("taliyahAdversaire" T) ("galioDispoLane" T)) (list "galioContre"  1)) 
(ajouteRegle '(("galioAdversaire" T) ("taliyahDispoLane" T)) (list "taliyahContre"  -1))
(ajouteRegle '(("brandAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  1)) 
(ajouteRegle '(("neekoAdversaire" T) ("brandDispoLane" T)) (list "brandContre"  -1))
(ajouteRegle '(("sivirAdversaire" T) ("twitchDispoLane" T)) (list "twitchContre"  1)) 
(ajouteRegle '(("twitchAdversaire" T) ("sivirDispoLane" T)) (list "sivirContre"  -1))
(ajouteRegle '(("cassiopeiaAdversaire" T) ("leblancDispoLane" T)) (list "leblancContre"  1)) 
(ajouteRegle '(("leblancAdversaire" T) ("cassiopeiaDispoLane" T)) (list "cassiopeiaContre"  -1))
(ajouteRegle '(("swainAdversaire" T) ("sylasDispoLane" T)) (list "sylasContre"  1)) 
(ajouteRegle '(("sylasAdversaire" T) ("swainDispoLane" T)) (list "swainContre"  -1))
(ajouteRegle '(("shacoAdversaire" T) ("sennaDispoLane" T)) (list "sennaContre"  1)) 
(ajouteRegle '(("sennaAdversaire" T) ("shacoDispoLane" T)) (list "shacoContre"  -1))
(ajouteRegle '(("akshanAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  1)) 
(ajouteRegle '(("chogathAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  -1))
(ajouteRegle '(("gragasAdversaire" T) ("ivernDispoLane" T)) (list "ivernContre"  1)) 
(ajouteRegle '(("ivernAdversaire" T) ("gragasDispoLane" T)) (list "gragasContre"  -1))
(ajouteRegle '(("apheliosAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  1)) 
(ajouteRegle '(("yasuoAdversaire" T) ("apheliosDispoLane" T)) (list "apheliosContre"  -1))
(ajouteRegle '(("talonAdversaire" T) ("cassiopeiaDispoLane" T)) (list "cassiopeiaContre"  1)) 
(ajouteRegle '(("cassiopeiaAdversaire" T) ("talonDispoLane" T)) (list "talonContre"  -1))
(ajouteRegle '(("sylasAdversaire" T) ("ireliaDispoLane" T)) (list "ireliaContre"  1)) 
(ajouteRegle '(("ireliaAdversaire" T) ("sylasDispoLane" T)) (list "sylasContre"  -1))
(ajouteRegle '(("swainAdversaire" T) ("sorakaDispoLane" T)) (list "sorakaContre"  1)) 
(ajouteRegle '(("sorakaAdversaire" T) ("swainDispoLane" T)) (list "swainContre"  -1))
(ajouteRegle '(("gnarAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  1)) 
(ajouteRegle '(("yasuoAdversaire" T) ("gnarDispoLane" T)) (list "gnarContre"  -1))
(ajouteRegle '(("udyrAdversaire" T) ("reksaiDispoLane" T)) (list "reksaiContre"  1)) 
(ajouteRegle '(("reksaiAdversaire" T) ("udyrDispoLane" T)) (list "udyrContre"  -1))
(ajouteRegle '(("karthusAdversaire" T) ("hecarimDispoLane" T)) (list "hecarimContre"  1)) 
(ajouteRegle '(("hecarimAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  -1))
(ajouteRegle '(("heimerdingerAdversaire" T) ("gnarDispoLane" T)) (list "gnarContre"  1)) 
(ajouteRegle '(("gnarAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  -1))
(ajouteRegle '(("taricAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  1)) 
(ajouteRegle '(("seraphineAdversaire" T) ("taricDispoLane" T)) (list "taricContre"  -1))
(ajouteRegle '(("kennenAdversaire" T) ("jayceDispoLane" T)) (list "jayceContre"  1)) 
(ajouteRegle '(("jayceAdversaire" T) ("kennenDispoLane" T)) (list "kennenContre"  -1))
(ajouteRegle '(("amumuAdversaire" T) ("jinxDispoLane" T)) (list "jinxContre"  1)) 
(ajouteRegle '(("jinxAdversaire" T) ("amumuDispoLane" T)) (list "amumuContre"  -1))
(ajouteRegle '(("quinnAdversaire" T) ("kennenDispoLane" T)) (list "kennenContre"  1)) 
(ajouteRegle '(("kennenAdversaire" T) ("quinnDispoLane" T)) (list "quinnContre"  -1))
(ajouteRegle '(("yasuoAdversaire" T) ("amumuDispoLane" T)) (list "amumuContre"  1)) 
(ajouteRegle '(("amumuAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  -1))
(ajouteRegle '(("taliyahAdversaire" T) ("khazixDispoLane" T)) (list "khazixContre"  1)) 
(ajouteRegle '(("khazixAdversaire" T) ("taliyahDispoLane" T)) (list "taliyahContre"  -1))
(ajouteRegle '(("neekoAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  1)) 
(ajouteRegle '(("malphiteAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  -1))
(ajouteRegle '(("jayceAdversaire" T) ("lissandraDispoLane" T)) (list "lissandraContre"  1)) 
(ajouteRegle '(("lissandraAdversaire" T) ("jayceDispoLane" T)) (list "jayceContre"  -1))
(ajouteRegle '(("poppyAdversaire" T) ("sionDispoLane" T)) (list "sionContre"  1)) 
(ajouteRegle '(("sionAdversaire" T) ("poppyDispoLane" T)) (list "poppyContre"  -1))
(ajouteRegle '(("mordekaiserAdversaire" T) ("kindredDispoLane" T)) (list "kindredContre"  1)) 
(ajouteRegle '(("kindredAdversaire" T) ("mordekaiserDispoLane" T)) (list "mordekaiserContre"  -1))
(ajouteRegle '(("gragasAdversaire" T) ("trundleDispoLane" T)) (list "trundleContre"  1)) 
(ajouteRegle '(("trundleAdversaire" T) ("gragasDispoLane" T)) (list "gragasContre"  -1))
(ajouteRegle '(("vladimirAdversaire" T) ("aatroxDispoLane" T)) (list "aatroxContre"  1)) 
(ajouteRegle '(("aatroxAdversaire" T) ("vladimirDispoLane" T)) (list "vladimirContre"  -1))
(ajouteRegle '(("ziggsAdversaire" T) ("vladimirDispoLane" T)) (list "vladimirContre"  1)) 
(ajouteRegle '(("vladimirAdversaire" T) ("ziggsDispoLane" T)) (list "ziggsContre"  -1))
(ajouteRegle '(("qiyanaAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  1)) 
(ajouteRegle '(("karthusAdversaire" T) ("qiyanaDispoLane" T)) (list "qiyanaContre"  -1))
(ajouteRegle '(("ryzeAdversaire" T) ("taliyahDispoLane" T)) (list "taliyahContre"  1)) 
(ajouteRegle '(("taliyahAdversaire" T) ("ryzeDispoLane" T)) (list "ryzeContre"  -1))
(ajouteRegle '(("volibearAdversaire" T) ("kennenDispoLane" T)) (list "kennenContre"  1)) 
(ajouteRegle '(("kennenAdversaire" T) ("volibearDispoLane" T)) (list "volibearContre"  -1))
(ajouteRegle '(("dianaAdversaire" T) ("fiddlesticksDispoLane" T)) (list "fiddlesticksContre"  1)) 
(ajouteRegle '(("fiddlesticksAdversaire" T) ("dianaDispoLane" T)) (list "dianaContre"  -1))
(ajouteRegle '(("heimerdingerAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  1)) 
(ajouteRegle '(("karthusAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  -1))
(ajouteRegle '(("ivernAdversaire" T) ("kaynDispoLane" T)) (list "kaynContre"  1)) 
(ajouteRegle '(("kaynAdversaire" T) ("ivernDispoLane" T)) (list "ivernContre"  -1))
(ajouteRegle '(("shenAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  1)) 
(ajouteRegle '(("seraphineAdversaire" T) ("shenDispoLane" T)) (list "shenContre"  -1))
(ajouteRegle '(("shyvanaAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("shyvanaDispoLane" T)) (list "shyvanaContre"  -1))
(ajouteRegle '(("pantheonAdversaire" T) ("corkiDispoLane" T)) (list "corkiContre"  1)) 
(ajouteRegle '(("corkiAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  -1))
(ajouteRegle '(("warwickAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  1)) 
(ajouteRegle '(("lilliaAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  -1))
(ajouteRegle '(("renektonAdversaire" T) ("jayceDispoLane" T)) (list "jayceContre"  1)) 
(ajouteRegle '(("jayceAdversaire" T) ("renektonDispoLane" T)) (list "renektonContre"  -1))
(ajouteRegle '(("cassiopeiaAdversaire" T) ("ziggsDispoLane" T)) (list "ziggsContre"  1)) 
(ajouteRegle '(("ziggsAdversaire" T) ("cassiopeiaDispoLane" T)) (list "cassiopeiaContre"  -1))
(ajouteRegle '(("volibearAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  1)) 
(ajouteRegle '(("lilliaAdversaire" T) ("volibearDispoLane" T)) (list "volibearContre"  -1))
(ajouteRegle '(("gragasAdversaire" T) ("threshDispoLane" T)) (list "threshContre"  1)) 
(ajouteRegle '(("threshAdversaire" T) ("gragasDispoLane" T)) (list "gragasContre"  -1))
(ajouteRegle '(("skarnerAdversaire" T) ("aatroxDispoLane" T)) (list "aatroxContre"  1)) 
(ajouteRegle '(("aatroxAdversaire" T) ("skarnerDispoLane" T)) (list "skarnerContre"  -1))
(ajouteRegle '(("lilliaAdversaire" T) ("quinnDispoLane" T)) (list "quinnContre"  1)) 
(ajouteRegle '(("quinnAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  -1))
(ajouteRegle '(("kalistaAdversaire" T) ("lucianDispoLane" T)) (list "lucianContre"  1)) 
(ajouteRegle '(("lucianAdversaire" T) ("kalistaDispoLane" T)) (list "kalistaContre"  -1))
(ajouteRegle '(("akshanAdversaire" T) ("dravenDispoLane" T)) (list "dravenContre"  1)) 
(ajouteRegle '(("dravenAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  -1))
(ajouteRegle '(("cassiopeiaAdversaire" T) ("drmundoDispoLane" T)) (list "drmundoContre"  1)) 
(ajouteRegle '(("drmundoAdversaire" T) ("cassiopeiaDispoLane" T)) (list "cassiopeiaContre"  -1))
(ajouteRegle '(("rengarAdversaire" T) ("evelynnDispoLane" T)) (list "evelynnContre"  1)) 
(ajouteRegle '(("evelynnAdversaire" T) ("rengarDispoLane" T)) (list "rengarContre"  -1))
(ajouteRegle '(("monkeykingAdversaire" T) ("evelynnDispoLane" T)) (list "evelynnContre"  1)) 
(ajouteRegle '(("evelynnAdversaire" T) ("monkeykingDispoLane" T)) (list "monkeykingContre"  -1))
(ajouteRegle '(("karthusAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  1)) 
(ajouteRegle '(("annieAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  -1))
(ajouteRegle '(("vexAdversaire" T) ("fiddlesticksDispoLane" T)) (list "fiddlesticksContre"  1)) 
(ajouteRegle '(("fiddlesticksAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  -1))
(ajouteRegle '(("galioAdversaire" T) ("shacoDispoLane" T)) (list "shacoContre"  1)) 
(ajouteRegle '(("shacoAdversaire" T) ("galioDispoLane" T)) (list "galioContre"  -1))
(ajouteRegle '(("illaoiAdversaire" T) ("urgotDispoLane" T)) (list "urgotContre"  1)) 
(ajouteRegle '(("urgotAdversaire" T) ("illaoiDispoLane" T)) (list "illaoiContre"  -1))
(ajouteRegle '(("syndraAdversaire" T) ("threshDispoLane" T)) (list "threshContre"  1)) 
(ajouteRegle '(("threshAdversaire" T) ("syndraDispoLane" T)) (list "syndraContre"  -1))
(ajouteRegle '(("rumbleAdversaire" T) ("camilleDispoLane" T)) (list "camilleContre"  1)) 
(ajouteRegle '(("camilleAdversaire" T) ("rumbleDispoLane" T)) (list "rumbleContre"  -1))
(ajouteRegle '(("maokaiAdversaire" T) ("vladimirDispoLane" T)) (list "vladimirContre"  1)) 
(ajouteRegle '(("vladimirAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  -1))
(ajouteRegle '(("veigarAdversaire" T) ("blitzcrankDispoLane" T)) (list "blitzcrankContre"  1)) 
(ajouteRegle '(("blitzcrankAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  -1))
(ajouteRegle '(("aniviaAdversaire" T) ("jinxDispoLane" T)) (list "jinxContre"  1)) 
(ajouteRegle '(("jinxAdversaire" T) ("aniviaDispoLane" T)) (list "aniviaContre"  -1))
(ajouteRegle '(("azirAdversaire" T) ("zoeDispoLane" T)) (list "zoeContre"  1)) 
(ajouteRegle '(("zoeAdversaire" T) ("azirDispoLane" T)) (list "azirContre"  -1))
(ajouteRegle '(("jaxAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  1)) 
(ajouteRegle '(("warwickAdversaire" T) ("jaxDispoLane" T)) (list "jaxContre"  -1))
(ajouteRegle '(("varusAdversaire" T) ("yuumiDispoLane" T)) (list "yuumiContre"  1)) 
(ajouteRegle '(("yuumiAdversaire" T) ("varusDispoLane" T)) (list "varusContre"  -1))
(ajouteRegle '(("sejuaniAdversaire" T) ("akaliDispoLane" T)) (list "akaliContre"  1)) 
(ajouteRegle '(("akaliAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  -1))
(ajouteRegle '(("gangplankAdversaire" T) ("kassadinDispoLane" T)) (list "kassadinContre"  1)) 
(ajouteRegle '(("kassadinAdversaire" T) ("gangplankDispoLane" T)) (list "gangplankContre"  -1))
(ajouteRegle '(("neekoAdversaire" T) ("varusDispoLane" T)) (list "varusContre"  1)) 
(ajouteRegle '(("varusAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  -1))
(ajouteRegle '(("olafAdversaire" T) ("rengarDispoLane" T)) (list "rengarContre"  1)) 
(ajouteRegle '(("rengarAdversaire" T) ("olafDispoLane" T)) (list "olafContre"  -1))
(ajouteRegle '(("annieAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  1)) 
(ajouteRegle '(("veigarAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  -1))
(ajouteRegle '(("rengarAdversaire" T) ("akaliDispoLane" T)) (list "akaliContre"  1)) 
(ajouteRegle '(("akaliAdversaire" T) ("rengarDispoLane" T)) (list "rengarContre"  -1))
(ajouteRegle '(("trundleAdversaire" T) ("ziggsDispoLane" T)) (list "ziggsContre"  1)) 
(ajouteRegle '(("ziggsAdversaire" T) ("trundleDispoLane" T)) (list "trundleContre"  -1))
(ajouteRegle '(("pantheonAdversaire" T) ("sennaDispoLane" T)) (list "sennaContre"  1)) 
(ajouteRegle '(("sennaAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  -1))
(ajouteRegle '(("fiddlesticksAdversaire" T) ("luxDispoLane" T)) (list "luxContre"  1)) 
(ajouteRegle '(("luxAdversaire" T) ("fiddlesticksDispoLane" T)) (list "fiddlesticksContre"  -1))
(ajouteRegle '(("ivernAdversaire" T) ("sivirDispoLane" T)) (list "sivirContre"  1)) 
(ajouteRegle '(("sivirAdversaire" T) ("ivernDispoLane" T)) (list "ivernContre"  -1))
(ajouteRegle '(("heimerdingerAdversaire" T) ("karmaDispoLane" T)) (list "karmaContre"  1)) 
(ajouteRegle '(("karmaAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  -1))
(ajouteRegle '(("rumbleAdversaire" T) ("nidaleeDispoLane" T)) (list "nidaleeContre"  1)) 
(ajouteRegle '(("nidaleeAdversaire" T) ("rumbleDispoLane" T)) (list "rumbleContre"  -1))
(ajouteRegle '(("pantheonAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  1)) 
(ajouteRegle '(("gravesAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  -1))
(ajouteRegle '(("malphiteAdversaire" T) ("caitlynDispoLane" T)) (list "caitlynContre"  1)) 
(ajouteRegle '(("caitlynAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  -1))
(ajouteRegle '(("gwenAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("gwenDispoLane" T)) (list "gwenContre"  -1))
(ajouteRegle '(("ryzeAdversaire" T) ("gwenDispoLane" T)) (list "gwenContre"  1)) 
(ajouteRegle '(("gwenAdversaire" T) ("ryzeDispoLane" T)) (list "ryzeContre"  -1))
(ajouteRegle '(("shyvanaAdversaire" T) ("mordekaiserDispoLane" T)) (list "mordekaiserContre"  1)) 
(ajouteRegle '(("mordekaiserAdversaire" T) ("shyvanaDispoLane" T)) (list "shyvanaContre"  -1))
(ajouteRegle '(("twitchAdversaire" T) ("annieDispoLane" T)) (list "annieContre"  1)) 
(ajouteRegle '(("annieAdversaire" T) ("twitchDispoLane" T)) (list "twitchContre"  -1))
(ajouteRegle '(("olafAdversaire" T) ("akaliDispoLane" T)) (list "akaliContre"  1)) 
(ajouteRegle '(("akaliAdversaire" T) ("olafDispoLane" T)) (list "olafContre"  -1))
(ajouteRegle '(("camilleAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  1)) 
(ajouteRegle '(("malphiteAdversaire" T) ("camilleDispoLane" T)) (list "camilleContre"  -1))
(ajouteRegle '(("luluAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  1)) 
(ajouteRegle '(("heimerdingerAdversaire" T) ("luluDispoLane" T)) (list "luluContre"  -1))
(ajouteRegle '(("luxAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  1)) 
(ajouteRegle '(("heimerdingerAdversaire" T) ("luxDispoLane" T)) (list "luxContre"  -1))
(ajouteRegle '(("leesinAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  1)) 
(ajouteRegle '(("karthusAdversaire" T) ("leesinDispoLane" T)) (list "leesinContre"  -1))
(ajouteRegle '(("yasuoAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  1)) 
(ajouteRegle '(("veigarAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  -1))
(ajouteRegle '(("caitlynAdversaire" T) ("zileanDispoLane" T)) (list "zileanContre"  1)) 
(ajouteRegle '(("zileanAdversaire" T) ("caitlynDispoLane" T)) (list "caitlynContre"  -1))
(ajouteRegle '(("yoneAdversaire" T) ("teemoDispoLane" T)) (list "teemoContre"  1)) 
(ajouteRegle '(("teemoAdversaire" T) ("yoneDispoLane" T)) (list "yoneContre"  -1))
(ajouteRegle '(("jinxAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  1)) 
(ajouteRegle '(("heimerdingerAdversaire" T) ("jinxDispoLane" T)) (list "jinxContre"  -1))
(ajouteRegle '(("jhinAdversaire" T) ("blitzcrankDispoLane" T)) (list "blitzcrankContre"  1)) 
(ajouteRegle '(("blitzcrankAdversaire" T) ("jhinDispoLane" T)) (list "jhinContre"  -1))
(ajouteRegle '(("zedAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  1)) 
(ajouteRegle '(("yasuoAdversaire" T) ("zedDispoLane" T)) (list "zedContre"  -1))
(ajouteRegle '(("jayceAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  1)) 
(ajouteRegle '(("kayleAdversaire" T) ("jayceDispoLane" T)) (list "jayceContre"  -1))
(ajouteRegle '(("ireliaAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("ireliaDispoLane" T)) (list "ireliaContre"  -1))
(ajouteRegle '(("yuumiAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  1)) 
(ajouteRegle '(("pantheonAdversaire" T) ("yuumiDispoLane" T)) (list "yuumiContre"  -1))
(ajouteRegle '(("morganaAdversaire" T) ("missfortuneDispoLane" T)) (list "missfortuneContre"  1)) 
(ajouteRegle '(("missfortuneAdversaire" T) ("morganaDispoLane" T)) (list "morganaContre"  -1))
(ajouteRegle '(("jaxAdversaire" T) ("singedDispoLane" T)) (list "singedContre"  1)) 
(ajouteRegle '(("singedAdversaire" T) ("jaxDispoLane" T)) (list "jaxContre"  -1))
(ajouteRegle '(("yoneAdversaire" T) ("ahriDispoLane" T)) (list "ahriContre"  1)) 
(ajouteRegle '(("ahriAdversaire" T) ("yoneDispoLane" T)) (list "yoneContre"  -1))
(ajouteRegle '(("viktorAdversaire" T) ("singedDispoLane" T)) (list "singedContre"  1)) 
(ajouteRegle '(("singedAdversaire" T) ("viktorDispoLane" T)) (list "viktorContre"  -1))
(ajouteRegle '(("threshAdversaire" T) ("xerathDispoLane" T)) (list "xerathContre"  1)) 
(ajouteRegle '(("xerathAdversaire" T) ("threshDispoLane" T)) (list "threshContre"  -1))
(ajouteRegle '(("blitzcrankAdversaire" T) ("missfortuneDispoLane" T)) (list "missfortuneContre"  1)) 
(ajouteRegle '(("missfortuneAdversaire" T) ("blitzcrankDispoLane" T)) (list "blitzcrankContre"  -1))
(ajouteRegle '(("namiAdversaire" T) ("kogmawDispoLane" T)) (list "kogmawContre"  1)) 
(ajouteRegle '(("kogmawAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  -1))
(ajouteRegle '(("viAdversaire" T) ("mordekaiserDispoLane" T)) (list "mordekaiserContre"  1)) 
(ajouteRegle '(("mordekaiserAdversaire" T) ("viDispoLane" T)) (list "viContre"  -1))
(ajouteRegle '(("viegoAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("viegoDispoLane" T)) (list "viegoContre"  -1))
(ajouteRegle '(("gravesAdversaire" T) ("fiddlesticksDispoLane" T)) (list "fiddlesticksContre"  1)) 
(ajouteRegle '(("fiddlesticksAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  -1))
(ajouteRegle '(("masteryiAdversaire" T) ("viDispoLane" T)) (list "viContre"  1)) 
(ajouteRegle '(("viAdversaire" T) ("masteryiDispoLane" T)) (list "masteryiContre"  -1))
(ajouteRegle '(("teemoAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  1)) 
(ajouteRegle '(("malphiteAdversaire" T) ("teemoDispoLane" T)) (list "teemoContre"  -1))
(ajouteRegle '(("settAdversaire" T) ("kledDispoLane" T)) (list "kledContre"  1)) 
(ajouteRegle '(("kledAdversaire" T) ("settDispoLane" T)) (list "settContre"  -1))
(ajouteRegle '(("leonaAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  1)) 
(ajouteRegle '(("maokaiAdversaire" T) ("leonaDispoLane" T)) (list "leonaContre"  -1))
(ajouteRegle '(("vayneAdversaire" T) ("sonaDispoLane" T)) (list "sonaContre"  1)) 
(ajouteRegle '(("sonaAdversaire" T) ("vayneDispoLane" T)) (list "vayneContre"  -1))
(ajouteRegle '(("luxAdversaire" T) ("corkiDispoLane" T)) (list "corkiContre"  1)) 
(ajouteRegle '(("corkiAdversaire" T) ("luxDispoLane" T)) (list "luxContre"  -1))
(ajouteRegle '(("kaynAdversaire" T) ("lilliaDispoLane" T)) (list "lilliaContre"  1)) 
(ajouteRegle '(("lilliaAdversaire" T) ("kaynDispoLane" T)) (list "kaynContre"  -1))
(ajouteRegle '(("kassadinAdversaire" T) ("renektonDispoLane" T)) (list "renektonContre"  1)) 
(ajouteRegle '(("renektonAdversaire" T) ("kassadinDispoLane" T)) (list "kassadinContre"  -1))
(ajouteRegle '(("talonAdversaire" T) ("xinzhaoDispoLane" T)) (list "xinzhaoContre"  1)) 
(ajouteRegle '(("xinzhaoAdversaire" T) ("talonDispoLane" T)) (list "talonContre"  -1))
(ajouteRegle '(("dariusAdversaire" T) ("illaoiDispoLane" T)) (list "illaoiContre"  1)) 
(ajouteRegle '(("illaoiAdversaire" T) ("dariusDispoLane" T)) (list "dariusContre"  -1))
(ajouteRegle '(("tryndamereAdversaire" T) ("jaxDispoLane" T)) (list "jaxContre"  1)) 
(ajouteRegle '(("jaxAdversaire" T) ("tryndamereDispoLane" T)) (list "tryndamereContre"  -1))
(ajouteRegle '(("vexAdversaire" T) ("pantheonDispoLane" T)) (list "pantheonContre"  1)) 
(ajouteRegle '(("pantheonAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  -1))
(ajouteRegle '(("ezrealAdversaire" T) ("twitchDispoLane" T)) (list "twitchContre"  1)) 
(ajouteRegle '(("twitchAdversaire" T) ("ezrealDispoLane" T)) (list "ezrealContre"  -1))
(ajouteRegle '(("khazixAdversaire" T) ("rammusDispoLane" T)) (list "rammusContre"  1)) 
(ajouteRegle '(("rammusAdversaire" T) ("khazixDispoLane" T)) (list "khazixContre"  -1))
(ajouteRegle '(("shenAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  1)) 
(ajouteRegle '(("kayleAdversaire" T) ("shenDispoLane" T)) (list "shenContre"  -1))
(ajouteRegle '(("leblancAdversaire" T) ("yoneDispoLane" T)) (list "yoneContre"  1)) 
(ajouteRegle '(("yoneAdversaire" T) ("leblancDispoLane" T)) (list "leblancContre"  -1))
(ajouteRegle '(("drmundoAdversaire" T) ("yorickDispoLane" T)) (list "yorickContre"  1)) 
(ajouteRegle '(("yorickAdversaire" T) ("drmundoDispoLane" T)) (list "drmundoContre"  -1))
(ajouteRegle '(("katarinaAdversaire" T) ("swainDispoLane" T)) (list "swainContre"  1)) 
(ajouteRegle '(("swainAdversaire" T) ("katarinaDispoLane" T)) (list "katarinaContre"  -1))
(ajouteRegle '(("sorakaAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  1)) 
(ajouteRegle '(("veigarAdversaire" T) ("sorakaDispoLane" T)) (list "sorakaContre"  -1))
(ajouteRegle '(("shacoAdversaire" T) ("dianaDispoLane" T)) (list "dianaContre"  1)) 
(ajouteRegle '(("dianaAdversaire" T) ("shacoDispoLane" T)) (list "shacoContre"  -1))
(ajouteRegle '(("pykeAdversaire" T) ("threshDispoLane" T)) (list "threshContre"  1)) 
(ajouteRegle '(("threshAdversaire" T) ("pykeDispoLane" T)) (list "pykeContre"  -1))
(ajouteRegle '(("fioraAdversaire" T) ("nasusDispoLane" T)) (list "nasusContre"  1)) 
(ajouteRegle '(("nasusAdversaire" T) ("fioraDispoLane" T)) (list "fioraContre"  -1))
(ajouteRegle '(("nasusAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  1)) 
(ajouteRegle '(("chogathAdversaire" T) ("nasusDispoLane" T)) (list "nasusContre"  -1))
(ajouteRegle '(("hecarimAdversaire" T) ("viegoDispoLane" T)) (list "viegoContre"  1)) 
(ajouteRegle '(("viegoAdversaire" T) ("hecarimDispoLane" T)) (list "hecarimContre"  -1))
(ajouteRegle '(("lucianAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  1)) 
(ajouteRegle '(("yasuoAdversaire" T) ("lucianDispoLane" T)) (list "lucianContre"  -1))
(ajouteRegle '(("rakanAdversaire" T) ("zileanDispoLane" T)) (list "zileanContre"  1)) 
(ajouteRegle '(("zileanAdversaire" T) ("rakanDispoLane" T)) (list "rakanContre"  -1))
(ajouteRegle '(("nautilusAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  1)) 
(ajouteRegle '(("namiAdversaire" T) ("nautilusDispoLane" T)) (list "nautilusContre"  -1))
(ajouteRegle '(("tahmkenchAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  1)) 
(ajouteRegle '(("heimerdingerAdversaire" T) ("tahmkenchDispoLane" T)) (list "tahmkenchContre"  -1))
(ajouteRegle '(("ekkoAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  1)) 
(ajouteRegle '(("warwickAdversaire" T) ("ekkoDispoLane" T)) (list "ekkoContre"  -1))
(ajouteRegle '(("sylasAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  1)) 
(ajouteRegle '(("kayleAdversaire" T) ("sylasDispoLane" T)) (list "sylasContre"  -1))
(ajouteRegle '(("karmaAdversaire" T) ("lucianDispoLane" T)) (list "lucianContre"  1)) 
(ajouteRegle '(("lucianAdversaire" T) ("karmaDispoLane" T)) (list "karmaContre"  -1))
(ajouteRegle '(("xinzhaoAdversaire" T) ("monkeykingDispoLane" T)) (list "monkeykingContre"  1)) 
(ajouteRegle '(("monkeykingAdversaire" T) ("xinzhaoDispoLane" T)) (list "xinzhaoContre"  -1))
(ajouteRegle '(("malphiteAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  -1))
(ajouteRegle '(("warwickAdversaire" T) ("zacDispoLane" T)) (list "zacContre"  1)) 
(ajouteRegle '(("zacAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  -1))
(ajouteRegle '(("missfortuneAdversaire" T) ("luxDispoLane" T)) (list "luxContre"  1)) 
(ajouteRegle '(("luxAdversaire" T) ("missfortuneDispoLane" T)) (list "missfortuneContre"  -1))
(ajouteRegle '(("garenAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  1)) 
(ajouteRegle '(("chogathAdversaire" T) ("garenDispoLane" T)) (list "garenContre"  -1))
(ajouteRegle '(("jannaAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  1)) 
(ajouteRegle '(("namiAdversaire" T) ("jannaDispoLane" T)) (list "jannaContre"  -1))
(ajouteRegle '(("akaliAdversaire" T) ("neekoDispoLane" T)) (list "neekoContre"  1)) 
(ajouteRegle '(("neekoAdversaire" T) ("akaliDispoLane" T)) (list "akaliContre"  -1))
(ajouteRegle '(("chogathAdversaire" T) ("gragasDispoLane" T)) (list "gragasContre"  1)) 
(ajouteRegle '(("gragasAdversaire" T) ("chogathDispoLane" T)) (list "chogathContre"  -1))
(ajouteRegle '(("urgotAdversaire" T) ("shyvanaDispoLane" T)) (list "shyvanaContre"  1)) 
(ajouteRegle '(("shyvanaAdversaire" T) ("urgotDispoLane" T)) (list "urgotContre"  -1))
(ajouteRegle '(("xerathAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  1)) 
(ajouteRegle '(("akshanAdversaire" T) ("xerathDispoLane" T)) (list "xerathContre"  -1))
(ajouteRegle '(("ornnAdversaire" T) ("camilleDispoLane" T)) (list "camilleContre"  1)) 
(ajouteRegle '(("camilleAdversaire" T) ("ornnDispoLane" T)) (list "ornnContre"  -1))
(ajouteRegle '(("mordekaiserAdversaire" T) ("tahmkenchDispoLane" T)) (list "tahmkenchContre"  1)) 
(ajouteRegle '(("tahmkenchAdversaire" T) ("mordekaiserDispoLane" T)) (list "mordekaiserContre"  -1))
(ajouteRegle '(("sonaAdversaire" T) ("trundleDispoLane" T)) (list "trundleContre"  1)) 
(ajouteRegle '(("trundleAdversaire" T) ("sonaDispoLane" T)) (list "sonaContre"  -1))
(ajouteRegle '(("vladimirAdversaire" T) ("velkozDispoLane" T)) (list "velkozContre"  1)) 
(ajouteRegle '(("velkozAdversaire" T) ("vladimirDispoLane" T)) (list "vladimirContre"  -1))
(ajouteRegle '(("rivenAdversaire" T) ("renektonDispoLane" T)) (list "renektonContre"  1)) 
(ajouteRegle '(("renektonAdversaire" T) ("rivenDispoLane" T)) (list "rivenContre"  -1))
(ajouteRegle '(("sennaAdversaire" T) ("ezrealDispoLane" T)) (list "ezrealContre"  1)) 
(ajouteRegle '(("ezrealAdversaire" T) ("sennaDispoLane" T)) (list "sennaContre"  -1))
(ajouteRegle '(("zacAdversaire" T) ("monkeykingDispoLane" T)) (list "monkeykingContre"  1)) 
(ajouteRegle '(("monkeykingAdversaire" T) ("zacDispoLane" T)) (list "zacContre"  -1))
(ajouteRegle '(("gravesAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  1)) 
(ajouteRegle '(("kayleAdversaire" T) ("gravesDispoLane" T)) (list "gravesContre"  -1))
(ajouteRegle '(("jarvanivAdversaire" T) ("xinzhaoDispoLane" T)) (list "xinzhaoContre"  1)) 
(ajouteRegle '(("xinzhaoAdversaire" T) ("jarvanivDispoLane" T)) (list "jarvanivContre"  -1))
(ajouteRegle '(("nocturneAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  1)) 
(ajouteRegle '(("sejuaniAdversaire" T) ("nocturneDispoLane" T)) (list "nocturneContre"  -1))
(ajouteRegle '(("yasuoAdversaire" T) ("quinnDispoLane" T)) (list "quinnContre"  1)) 
(ajouteRegle '(("quinnAdversaire" T) ("yasuoDispoLane" T)) (list "yasuoContre"  -1))
(ajouteRegle '(("akshanAdversaire" T) ("twistedfateDispoLane" T)) (list "twistedfateContre"  1)) 
(ajouteRegle '(("twistedfateAdversaire" T) ("akshanDispoLane" T)) (list "akshanContre"  -1))
(ajouteRegle '(("trundleAdversaire" T) ("viDispoLane" T)) (list "viContre"  1)) 
(ajouteRegle '(("viAdversaire" T) ("trundleDispoLane" T)) (list "trundleContre"  -1))
(ajouteRegle '(("kayleAdversaire" T) ("tryndamereDispoLane" T)) (list "tryndamereContre"  1)) 
(ajouteRegle '(("tryndamereAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  -1))
(ajouteRegle '(("nunuAdversaire" T) ("jaxDispoLane" T)) (list "jaxContre"  1)) 
(ajouteRegle '(("jaxAdversaire" T) ("nunuDispoLane" T)) (list "nunuContre"  -1))
(ajouteRegle '(("vayneAdversaire" T) ("drmundoDispoLane" T)) (list "drmundoContre"  1)) 
(ajouteRegle '(("drmundoAdversaire" T) ("vayneDispoLane" T)) (list "vayneContre"  -1))
(ajouteRegle '(("twistedfateAdversaire" T) ("syndraDispoLane" T)) (list "syndraContre"  1)) 
(ajouteRegle '(("syndraAdversaire" T) ("twistedfateDispoLane" T)) (list "twistedfateContre"  -1))
(ajouteRegle '(("ahriAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  1)) 
(ajouteRegle '(("vexAdversaire" T) ("ahriDispoLane" T)) (list "ahriContre"  -1))
(ajouteRegle '(("zileanAdversaire" T) ("rellDispoLane" T)) (list "rellContre"  1)) 
(ajouteRegle '(("rellAdversaire" T) ("zileanDispoLane" T)) (list "zileanContre"  -1))
(ajouteRegle '(("veigarAdversaire" T) ("katarinaDispoLane" T)) (list "katarinaContre"  1)) 
(ajouteRegle '(("katarinaAdversaire" T) ("veigarDispoLane" T)) (list "veigarContre"  -1))
(ajouteRegle '(("asheAdversaire" T) ("rellDispoLane" T)) (list "rellContre"  1)) 
(ajouteRegle '(("rellAdversaire" T) ("asheDispoLane" T)) (list "asheContre"  -1))
(ajouteRegle '(("aurelionsolAdversaire" T) ("viktorDispoLane" T)) (list "viktorContre"  1)) 
(ajouteRegle '(("viktorAdversaire" T) ("aurelionsolDispoLane" T)) (list "aurelionsolContre"  -1))
(ajouteRegle '(("akaliAdversaire" T) ("teemoDispoLane" T)) (list "teemoContre"  1)) 
(ajouteRegle '(("teemoAdversaire" T) ("akaliDispoLane" T)) (list "akaliContre"  -1))
(ajouteRegle '(("zileanAdversaire" T) ("velkozDispoLane" T)) (list "velkozContre"  1)) 
(ajouteRegle '(("velkozAdversaire" T) ("zileanDispoLane" T)) (list "zileanContre"  -1))
(ajouteRegle '(("xerathAdversaire" T) ("zedDispoLane" T)) (list "zedContre"  1)) 
(ajouteRegle '(("zedAdversaire" T) ("xerathDispoLane" T)) (list "xerathContre"  -1))
(ajouteRegle '(("sionAdversaire" T) ("dariusDispoLane" T)) (list "dariusContre"  1)) 
(ajouteRegle '(("dariusAdversaire" T) ("sionDispoLane" T)) (list "sionContre"  -1))
(ajouteRegle '(("zedAdversaire" T) ("taliyahDispoLane" T)) (list "taliyahContre"  1)) 
(ajouteRegle '(("taliyahAdversaire" T) ("zedDispoLane" T)) (list "zedContre"  -1))
(ajouteRegle '(("sejuaniAdversaire" T) ("poppyDispoLane" T)) (list "poppyContre"  1)) 
(ajouteRegle '(("poppyAdversaire" T) ("sejuaniDispoLane" T)) (list "sejuaniContre"  -1))
(ajouteRegle '(("alistarAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  1)) 
(ajouteRegle '(("namiAdversaire" T) ("alistarDispoLane" T)) (list "alistarContre"  -1))
(ajouteRegle '(("brandAdversaire" T) ("sennaDispoLane" T)) (list "sennaContre"  1)) 
(ajouteRegle '(("sennaAdversaire" T) ("brandDispoLane" T)) (list "brandContre"  -1))
(ajouteRegle '(("ireliaAdversaire" T) ("heimerdingerDispoLane" T)) (list "heimerdingerContre"  1)) 
(ajouteRegle '(("heimerdingerAdversaire" T) ("ireliaDispoLane" T)) (list "ireliaContre"  -1))
(ajouteRegle '(("bardAdversaire" T) ("shacoDispoLane" T)) (list "shacoContre"  1)) 
(ajouteRegle '(("shacoAdversaire" T) ("bardDispoLane" T)) (list "bardContre"  -1))
(ajouteRegle '(("corkiAdversaire" T) ("rumbleDispoLane" T)) (list "rumbleContre"  1)) 
(ajouteRegle '(("rumbleAdversaire" T) ("corkiDispoLane" T)) (list "corkiContre"  -1))
(ajouteRegle '(("kaisaAdversaire" T) ("seraphineDispoLane" T)) (list "seraphineContre"  1)) 
(ajouteRegle '(("seraphineAdversaire" T) ("kaisaDispoLane" T)) (list "kaisaContre"  -1))
(ajouteRegle '(("aniviaAdversaire" T) ("malphiteDispoLane" T)) (list "malphiteContre"  1)) 
(ajouteRegle '(("malphiteAdversaire" T) ("aniviaDispoLane" T)) (list "aniviaContre"  -1))
(ajouteRegle '(("nidaleeAdversaire" T) ("eliseDispoLane" T)) (list "eliseContre"  1)) 
(ajouteRegle '(("eliseAdversaire" T) ("nidaleeDispoLane" T)) (list "nidaleeContre"  -1))
(ajouteRegle '(("dravenAdversaire" T) ("maokaiDispoLane" T)) (list "maokaiContre"  1)) 
(ajouteRegle '(("maokaiAdversaire" T) ("dravenDispoLane" T)) (list "dravenContre"  -1))
(ajouteRegle '(("gangplankAdversaire" T) ("illaoiDispoLane" T)) (list "illaoiContre"  1)) 
(ajouteRegle '(("illaoiAdversaire" T) ("gangplankDispoLane" T)) (list "gangplankContre"  -1))
(ajouteRegle '(("braumAdversaire" T) ("namiDispoLane" T)) (list "namiContre"  1)) 
(ajouteRegle '(("namiAdversaire" T) ("braumDispoLane" T)) (list "braumContre"  -1))
(ajouteRegle '(("twitchAdversaire" T) ("swainDispoLane" T)) (list "swainContre"  1)) 
(ajouteRegle '(("swainAdversaire" T) ("twitchDispoLane" T)) (list "twitchContre"  -1))
(ajouteRegle '(("zyraAdversaire" T) ("ziggsDispoLane" T)) (list "ziggsContre"  1)) 
(ajouteRegle '(("ziggsAdversaire" T) ("zyraDispoLane" T)) (list "zyraContre"  -1))
(ajouteRegle '(("rammusAdversaire" T) ("warwickDispoLane" T)) (list "warwickContre"  1)) 
(ajouteRegle '(("warwickAdversaire" T) ("rammusDispoLane" T)) (list "rammusContre"  -1))
(ajouteRegle '(("karthusAdversaire" T) ("vayneDispoLane" T)) (list "vayneContre"  1)) 
(ajouteRegle '(("vayneAdversaire" T) ("karthusDispoLane" T)) (list "karthusContre"  -1))
(ajouteRegle '(("viktorAdversaire" T) ("ireliaDispoLane" T)) (list "ireliaContre"  1)) 
(ajouteRegle '(("ireliaAdversaire" T) ("viktorDispoLane" T)) (list "viktorContre"  -1))
(ajouteRegle '(("kindredAdversaire" T) ("jaxDispoLane" T)) (list "jaxContre"  1)) 
(ajouteRegle '(("jaxAdversaire" T) ("kindredDispoLane" T)) (list "kindredContre"  -1))
(ajouteRegle '(("syndraAdversaire" T) ("vexDispoLane" T)) (list "vexContre"  1)) 
(ajouteRegle '(("vexAdversaire" T) ("syndraDispoLane" T)) (list "syndraContre"  -1))
(ajouteRegle '(("kayleAdversaire" T) ("zileanDispoLane" T)) (list "zileanContre"  1)) 
(ajouteRegle '(("zileanAdversaire" T) ("kayleDispoLane" T)) (list "kayleContre"  -1))


;;
  (loop for champion in liste_champions do
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")0))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")1))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")2))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")3))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")4))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")5))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")6))
                     (list (concatenate 'string champion "Choix")T)))
  (loop for champion in liste_champions do 
        (ajouteRegle (list(list (concatenate 'string champion "Jouable")T) (list (concatenate 'string champion "Contre")7))
                     (list (concatenate 'string champion "Choix")T)))
)



(remplir_regles)

;; fonction qui renvoie T si les conditions d une regle sont satisfaites, Nil sinon
(defun regle_verifie (regle)
  (let ((flag T))               
    (loop for fait in (car regle) do
        (if (not (member fait faits :test #'equal))
            (setq flag Nil)
          ))
    flag
    ))


;; le moteur avant 
(defun moteur_avant (flag)
  (loop for regle in regles do
      (if (regle_verifie regle)
          (loop for fait in (cdr regle) do
                ;;(print "on va ajouter le fait suivant")
                ;;(print fait)
                (if (numberp (cadr fait)) (ajouteFaitContre fait) (ajouteFait fait))
                (setq regles (remove regle regles :test #'equal))
                (setq flag T)
                (setq iteration (+ iteration 1))
                ))
  (setq iteration (+ iteration 1)))
  (if flag (moteur_avant nil)))

(defun afficher_resultat (bdf)
  (loop for champion in liste_champions do
        (if (member (list (concatenate 'string champion "Choix")T) faits :test #'equal)
            (format t "~%on peut choisir le champion ~s"champion)))
)

(defun afficher_bdr (bdr)
  (let ((cpt 0))
    (loop for regle in bdr do
          (setq cpt (+ 1 cpt))
          (format t "~% Regle n°~s : ~s" cpt regle))))


;;(afficher_bdr regles)
(moteur_avant nil)
;;(afficher_bdr regles)
;;(loop for fait in faits do (print fait))
;;(nombre_contre "camille")
(nombre_contre "garen")
(afficher_resultat faits)
                                            
(format t "~%On a effectue ~s iterations"iteration)
